version: '3.9'

networks:
  default:

services:
  api:
    container_name: anlixapi
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=postgresdb
    ports:
      - "3000:3000"
      - "30000:30000"
    volumes:
      - ./api/src:/app/src
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anlix_challenge
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
